### 1. Basic Concepts (1-20)

1. What is Pandas, and why is it used?
2. What are the key features of the Pandas library?
3. What are the main data structures in Pandas?
4. Define Series in Pandas.
5. Define DataFrame in Pandas.
6. How do you create a Series?
7. How do you create a DataFrame?
8. What is the difference between loc and iloc?
9. How do you handle missing data in Pandas?
10. What is indexing in Pandas?
11. How do you read a CSV file into a DataFrame?
12. How do you write a DataFrame to a CSV file?
13. What is the purpose of the shape attribute?
14. How do you check for missing values in a DataFrame?
15. How do you drop rows with missing values?
16. What is the difference between dropna() and fillna()?
17. How do you rename columns in a DataFrame?
18. What is the purpose of the describe() function?
19. How do you select specific columns from a DataFrame?
20. What is the difference between head() and tail()?

In [1]:
import pandas as pd
import numpy as np

# 1. What is Pandas, and why is it used?
# Pandas is a powerful Python library used for data manipulation and analysis.
# It provides labeled data structures like Series and DataFrame for efficient data handling.

# 2. What are the key features of the Pandas library?
# Label-based indexing, handling missing data, groupby, merging, reshaping, time-series support, etc.

# 3. What are the main data structures in Pandas?
# Series (1D), DataFrame (2D), and Panel (3D - deprecated).

In [6]:
# Pandas is an open-source Python library for data manipulation and analysis. It provides data structures like Series and DataFrame for handling structured data efficiently. Built on NumPy, it simplifies tasks like data cleaning, transformation, and analysis.

# Why it is used:
# - Simplifies data loading from various formats (CSV, Excel, JSON, etc.).
# - Handles missing data and data cleaning tasks effectively.
# - Enables data transformation, filtering, grouping, and merging.
# - Supports time series analysis and statistical computations.
# - Integrates with visualization libraries like Matplotlib and Seaborn.
# - Ideal for data science, machine learning, and analytics tasks.

# Example context:
# Without Pandas, tasks like filtering rows or merging datasets would require complex, error-prone custom code. Pandas reduces this to a few lines.

In [7]:
# Key features of Pandas:
# - **Data Structures**: Series (1D) and DataFrame (2D) for structured data.
# - **Data I/O**: Read/write data from/to CSV, Excel, JSON, SQL, etc.
# - **Data Cleaning**: Handle missing values, duplicates, and type conversions.
# - **Data Transformation**: Filtering, sorting, grouping, merging, and reshaping data.
# - **Time Series**: Tools for datetime handling, resampling, and rolling calculations.
# - **Statistical Tools**: Descriptive statistics, correlation, and aggregations.
# - **Visualization**: Built-in plotting functions for quick data visualization.
# - **Performance**: Vectorized operations and integration with NumPy for efficiency.
# - **Extensibility**: Works seamlessly with other libraries like Scikit-learn and Matplotlib.

# Example:
# Loading data, cleaning it, and plotting are all streamlined with Pandas.

In [9]:
# Pandas has two primary data structures:
# - **Series**: A one-dimensional labeled array for homogeneous data, similar to a column in a spreadsheet.
# - **DataFrame**: A two-dimensional labeled table for heterogeneous data, like a spreadsheet or SQL table.

# Example:
# Series
series = pd.Series([1, 2, 3], index=['a', 'b', 'c'])
print(series)
# Output:
# a    1
# b    2
# c    3
# dtype: int64

a    1
b    2
c    3
dtype: int64

In [11]:
# DataFrame
data = {'col1': [1, 2], 'col2': ['A', 'B']}
df = pd.DataFrame(data)
print(df)

   col1 col2
0     1    A
1     2    B

In [5]:
# 4. Define Series in Pandas.
series = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
series = pd.Series([10, 20, 30], index=['A', 'B', 'C'])
print(series)

A    10
B    20
C    30
dtype: int64

In [12]:
# Key characteristics:
# - Heterogeneous data (columns can have different types).
# - Indexed rows and labeled columns.
# - Supports operations like filtering, grouping, and merging.

# Example:
data = {'Name': ['Alice', 'Bob'], 'Age': [25, 30]}
df = pd.DataFrame(data, index=['ID1', 'ID2'])
print(df)
# Output:
#      Name  Age
# ID1  Alice   25
# ID2    Bob   30

      Name  Age
ID1  Alice   25
ID2    Bob   30

In [13]:
# A Series can be created in multiple ways:

# Method 1: From a list
series1 = pd.Series([1, 2, 3], index=['a', 'b', 'c'])
print(series1)

# Method 2: From a dictionary
data = {'a': 1, 'b': 2, 'c': 3}
series2 = pd.Series(data)
print(series2)

# Method 3: From a NumPy array
array = np.array([10, 20, 30])
series3 = pd.Series(array, index=['x', 'y', 'z'])
print(series3)

# Method 4: From a scalar with an index
series4 = pd.Series(5, index=['a', 'b', 'c'])
print(series4)

# Output (for all methods):
# a    1
# b    2
# c    3
# dtype: int64 (or similar for other examples)

a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
dtype: int64
x    10
y    20
z    30
dtype: int64
a    5
b    5
c    5
dtype: int64

In [17]:
# A DataFrame can be created in multiple ways:

# Method 1: From a dictionary of lists
data = {'Name': ['Alice', 'Bob'], 'Age': [25, 30]}
df1 = pd.DataFrame(data)
print(df1)

# Method 2: From a list of dictionaries
data = [{'Name': 'Alice', 'Age': 25}, {'Name': 'Bob', 'Age': 30}]
df2 = pd.DataFrame(data)
print(df2)

# Method 3: From a NumPy array with column names and index
array = np.array([[1, 2], [3, 4]])
df3 = pd.DataFrame(array, columns=['A', 'B'], index=['x', 'y'])
print(df3)

# Method 4: From a list of lists with column names
data = [['Alice', 25], ['Bob', 30]]
df4 = pd.DataFrame(data, columns=['Name', 'Age'])
print(df4)

# Output (for df1 and df4):
#     Name  Age
# 0  Alice   25
# 1    Bob   30

    Name  Age
0  Alice   25
1    Bob   30
    Name  Age
0  Alice   25
1    Bob   30
   A  B
x  1  2
y  3  4
    Name  Age
0  Alice   25
1    Bob   30

In [14]:
data = {'Name': ['Alice', 'Bob'], 'Age': [25, 30]}
df1 = pd.DataFrame(data=data)
df1

    Name  Age
0  Alice   25
1    Bob   30

In [16]:
data = [{'Name': 'Alice', 'Age': 25},  {'Name': 'Bob', 'Age': 30}]
df2 = pd.DataFrame(data)
df2

    Name  Age
0  Alice   25
1    Bob   30

In [18]:
array = np.array([[1, 2], [3, 4]])
df3 = pd.DataFrame(array, columns=['A', 'B'], index=['x', 'y'])
print(df3)

   A  B
x  1  2
y  3  4

In [19]:
data = [['Alice', 25], ['Bob', 30]]
df4 = pd.DataFrame(data, columns=['Name', 'Age'])
print(df4)

    Name  Age
0  Alice   25
1    Bob   30

In [ ]:
# Missing data (NaN, None) can be handled using various methods:

# Method 1: Detect missing values
df = pd.DataFrame({'A': [1, np.nan, 3], 'B': [4, 5, np.nan]})
print(df,"\n")
print(df.isnull())  # Check for missing values
# Output:
#        A      B
# 0  False  False
# 1   True  False
# 2  False   True

# Method 2: Drop missing values
print(df.dropna())  # Drop rows with any missing values
# Output:
#      A    B
# 0  1.0  4.0

# Method 3: Fill missing values
print(df.fillna(0))  # Fill NaN with 0
# Output:
#      A    B
# 0  1.0  4.0
# 1  0.0  5.0
# 2  3.0  0.0

# Method 4: Fill with mean
print(df.fillna(df.mean()))  # Fill NaN with column mean
# Output:
#      A    B
# 0  1.0  4.0
# 1  2.0  5.0
# 2  3.0  4.5

# Method 5: Interpolate missing values
print(df.interpolate())  # Linear interpolation
# Output:
#      A    B
# 0  1.0  4.0
# 1  2.0  5.0
# 2  3.0  5.0

     A    B
0  1.0  4.0
1  NaN  5.0
2  3.0  NaN

       A      B
0  False  False
1   True  False
2  False   True
     A    B
0  1.0  4.0
     A    B
0  1.0  4.0
1  0.0  5.0
2  3.0  0.0
     A    B
0  1.0  4.0
1  2.0  5.0
2  3.0  4.5
     A    B
0  1.0  4.0
1  2.0  5.0
2  3.0  5.0

#### **10. What is indexing in Pandas?**

In [ ]:
# Indexing in Pandas refers to selecting subsets of data using labels or positions.
# - Series: Uses a single index (labels or integers).
# - DataFrame: Uses row and column indices (labels or integers).

# Example:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]}, index=['x', 'y', 'z'])

# Label-based indexing with loc
print(df.loc['x'])  # Select row 'x'
# Output:
# A    1
# B    4
# Name: x, dtype: int64

# Position-based indexing with iloc
print(df.iloc[0])  # Select first row
# Output:
# A    1
# B    4
# Name: x, dtype: int64

# Setting a custom index
df.set_index('A', inplace=True)
print(df)
# Output:
#    B
# A   
# 1  4
# 2  5
# 3  6

In [22]:
import pandas as pd
import numpy as np

data = {'value': [1, np.nan, np.nan, 4, 5]}
df = pd.DataFrame(data)

# Linear interpolation
interpolated_df = df.interpolate()

print(interpolated_df)

   value
0    1.0
1    2.0
2    3.0
3    4.0
4    5.0

In [26]:
import pandas as pd

# Sample DataFrame
data = {
    'ID': [101, 102, 103],
    'Name': ['Drishya', 'Rohit', 'Tanvi'],
    'Score': [85, 90, 95]
}

df = pd.DataFrame(data)
print(df)

    ID     Name  Score
0  101  Drishya     85
1  102    Rohit     90
2  103    Tanvi     95

In [27]:
# Set 'ID' column as index
df_custom = df.set_index('ID')
print(df_custom)

        Name  Score
ID
101  Drishya     85
102    Rohit     90
103    Tanvi     95

In [28]:
df2 = pd.DataFrame(data, index=data['ID'])
print(df2)

      ID     Name  Score
101  101  Drishya     85
102  102    Rohit     90
103  103    Tanvi     95

In [29]:
data = {
    'Date': ['2024-01-01', '2024-01-02', '2024-01-03'],
    'Sales': [200, 220, 250]
}
df = pd.DataFrame(data)

# Convert 'Date' to datetime type
df['Date'] = pd.to_datetime(df['Date'])

# Set it as index
df = df.set_index('Date')

print(df)

            Sales
Date
2024-01-01    200
2024-01-02    220
2024-01-03    250

In [ ]:
# Pandas provides pd.read_csv() to read CSV files with various options:

# Method 1: Basic reading
df = pd.read_csv('file.csv')
print(df)

# Method 2: Specify columns to load
df = pd.read_csv('file.csv', usecols=['column1', 'column2'])
print(df)

# Method 3: Set custom index
df = pd.read_csv('file.csv', index_col='ID')
print(df)

# Method 4: Handle large files with chunks
for chunk in pd.read_csv('file.csv', chunksize=1000):
    print(chunk.head())  # Process each chunk

# Method 5: Specify delimiter (e.g., for TSV)
df = pd.read_csv('file.tsv', sep='\t')
print(df)

# Example (assuming file.csv exists):
# df = pd.read_csv('file.csv')
# print(df.head())

In [31]:
# Pandas provides to_csv() to write DataFrames to CSV files:

# Method 1: Basic writing
df = pd.DataFrame({'A': [1, 2, 3, 9, 7, 6, 5], 'B': [4, 5, 6, 4, 3, 2, 1]})
df.to_csv('output.csv')

# Method 2: Exclude index
df.to_csv('output.csv', index=False)

# Method 3: Specify columns
df.to_csv('output.csv', columns=['A'])

# Method 4: Use a different delimiter
df.to_csv('output.tsv', sep='\t')

# Method 5: Append to existing file
df.to_csv('output.csv', mode='a', header=False)

# Example:
df.to_csv('output.csv', index=False)
# Creates a CSV file without the index column.

In [32]:
# The shape attribute returns a tuple representing the dimensions of a DataFrame or Series:
# - For DataFrame: (number of rows, number of columns).
# - For Series: (number of elements,).

# Example:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
print(df.shape)  # Output: (3, 2)

series = pd.Series([1, 2, 3])
print(series.shape)  # Output: (3,)

(3, 2)
(3,)

In [33]:
# Pandas provides methods to detect missing values (NaN, None):

# Method 1: Use isnull()
df = pd.DataFrame({'A': [1, np.nan, 3], 'B': [4, 5, np.nan]})
print(df.isnull())
# Output:
#        A      B
# 0  False  False
# 1   True  False
# 2  False   True

# Method 2: Use notnull()
print(df.notnull())
# Output:
#        A      B
# 0   True   True
# 1  False   True
# 2   True  False

# Method 3: Count missing values per column
print(df.isnull().sum())
# Output:
# A    1
# B    1
# dtype: int64

# Method 4: Total missing values
print(df.isnull().sum().sum())
# Output: 2

       A      B
0  False  False
1   True  False
2  False   True
       A      B
0   True   True
1  False   True
2   True  False
A    1
B    1
dtype: int64
2

In [34]:
# Use dropna() to remove rows (or columns) with missing values:

# Method 1: Drop rows with any missing values
df = pd.DataFrame({'A': [1, np.nan, 3], 'B': [4, 5, np.nan]})
print(df.dropna())
# Output:
#      A    B
# 0  1.0  4.0

# Method 2: Drop rows with all missing values
df = pd.DataFrame({'A': [np.nan, np.nan, 3], 'B': [np.nan, 5, np.nan]})
print(df.dropna(how='all'))
# Output:
#      A    B
# 1  NaN  5.0
# 2  3.0  NaN

# Method 3: Drop rows with missing values in specific columns
print(df.dropna(subset=['B']))
# Output:
#      A    B
# 1  NaN  5.0

# Method 4: Drop columns with missing values
print(df.dropna(axis=1))
# Output: (empty DataFrame if all columns have NaN)

     A    B
0  1.0  4.0
     A    B
1  NaN  5.0
2  3.0  NaN
    A    B
1 NaN  5.0
Empty DataFrame
Columns: []
Index: [0, 1, 2]

In [36]:
# dropna(): Removes rows or columns with missing values.
# fillna(): Replaces missing values with a specified value or method.

# Example with dropna():
df = pd.DataFrame({'A': [1, np.nan, 3], 'B': [4, 5, np.nan]})
print(df.dropna())  # Drops rows with any NaN
# Output:
#      A    B
# 0  1.0  4.0

# Example with fillna():
print(df.fillna(0))  # Fills NaN with 0
# Output:
#      A    B
# 0  1.0  4.0
# 1  0.0  5.0
# 2  3.0  0.0

# fillna() with method:
print(df.ffill())  # Forward fill
# Output:
#      A    B
# 0  1.0  4.0
# 1  1.0  5.0
# 2  3.0  5.0

# Key Differences:
# - dropna() reduces the dataset size; fillna() preserves it.
# - dropna() is for removal; fillna() is for imputation.

     A    B
0  1.0  4.0
     A    B
0  1.0  4.0
1  0.0  5.0
2  3.0  0.0
     A    B
0  1.0  4.0
1  1.0  5.0
2  3.0  5.0

In [42]:
# You can rename columns in multiple ways:

# Method 1: Use rename() with a dictionary
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
df.rename(columns={'A': 'Col1', 'B': 'Col2'}, inplace=True)
print(df)
# Output:
#    Col1  Col2
# 0     1     4
# 1     2     5
# 2     3     6

print("\n")
# Method 2: Assign new column names directly
df.columns = ['A', 'B']
print(df)
# Output: Same as above

print("\n")
# Method 3: Use rename() with a function
df.rename(columns=str.lower, inplace=True)
print(df)
# Output: (if columns were uppercase, they become lowercase)

print("\n")
# Method 4: Rename during DataFrame creation
df = pd.DataFrame([[1, 4], [2, 5], [3, 6]], columns=['Col1', 'Col2'])
print(df)
# Output: Same as above

   Col1  Col2
0     1     4
1     2     5
2     3     6


   A  B
0  1  4
1  2  5
2  3  6


   a  b
0  1  4
1  2  5
2  3  6


   Col1  Col2
0     1     4
1     2     5
2     3     6

In [43]:
# The describe() function generates descriptive statistics for numerical columns in a DataFrame, including count, mean, std, min, max, and quartiles.

# Example:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
print(df.describe())
# Output:
#              A         B
# count  3.000000  3.000000
# mean   2.000000  5.000000
# std    1.000000  1.000000
# min    1.000000  4.000000
# 25%    1.500000  4.500000
# 50%    2.000000  5.000000
# 75%    2.500000  5.500000
# max    3.000000  6.000000

# Method 2: Include all columns (including non-numerical)
df = pd.DataFrame({'A': [1, 2, 3], 'B': ['x', 'y', 'z']})
print(df.describe(include='all'))
# Output:
#               A    B
# count   3.000000    3
# unique       NaN    3
# top          NaN    x
# freq         NaN    1
# mean    2.000000  NaN
# std     1.000000  NaN
# min     1.000000  NaN
# 25%     1.500000  NaN
# 50%     2.000000  NaN
# 75%     2.500000  NaN
# max     3.000000  NaN

         A    B
count  3.0  3.0
mean   2.0  5.0
std    1.0  1.0
min    1.0  4.0
25%    1.5  4.5
50%    2.0  5.0
75%    2.5  5.5
max    3.0  6.0
          A    B
count   3.0    3
unique  NaN    3
top     NaN    x
freq    NaN    1
mean    2.0  NaN
std     1.0  NaN
min     1.0  NaN
25%     1.5  NaN
50%     2.0  NaN
75%     2.5  NaN
max     3.0  NaN

#### **19. How do you select specific columns from a DataFrame?**

In [ ]:
# You can select columns in multiple ways:

# Method 1: Using column names (single column)
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6], 'C': [7, 8, 9]})
print(df['A'])
# Output:
# 0    1
# 1    2
# 2    3
# Name: A, dtype: int64

# Method 2: Using column names (multiple columns)
print(df[['A', 'B']])
# Output:
#    A  B
# 0  1  4
# 1  2  5
# 2  3  6

# Method 3: Using loc for label-based selection
print(df.loc[:, ['A', 'B']])
# Output: Same as above

# Method 4: Using iloc for position-based selection
print(df.iloc[:, [0, 1]])
# Output: Same as above

# Method 5: Using filter() for pattern-based selection
print(df.filter(like='A'))
# Output:
#    A
# 0  1
# 1  2
# 2  3

In [44]:
import pandas as pd
import numpy as np

# Create a sample dataset mimicking real-world transaction data
data = {
    'CustomerID': ['C001', 'C002', 'C003', 'C004', 'C005'],
    'TransactionDate': ['2025-01-01', '2025-01-02', '2025-01-03', np.nan, '2025-01-05'],
    'ProductCategory': ['Electronics', 'Clothing', 'Books', 'Electronics', 'Clothing'],
    'Quantity': [2, 1, 3, 4, np.nan],
    'UnitPrice': [100.0, 50.0, 20.0, 150.0, 60.0],
    'TotalSpend': [200.0, 50.0, 60.0, 600.0, np.nan],
    'CustomerSegment': ['Premium', 'Regular', 'Regular', 'Premium', 'Regular'],
    'Region': ['North', 'South', 'East', 'West', 'North']
}
df = pd.DataFrame(data)

# Save to CSV for realistic file-based operations
df.to_csv('transactions.csv', index=False)

# Read the dataset
df = pd.read_csv('transactions.csv')
print("Original DataFrame:")
print(df)

# Method 1: Using column names (single column)
# Use case: Extract CustomerID for a unique customer list
print("\nMethod 1: Selecting 'CustomerID' column")
customer_ids = df['CustomerID']
print(customer_ids)
# Output:
# 0    C001
# 1    C002
# 2    C003
# 3    C004
# 4    C005
# Name: CustomerID, dtype: object

# Method 2: Using column names (multiple columns)
# Use case: Select columns for a report on customer spending
print("\nMethod 2: Selecting 'CustomerID' and 'TotalSpend' columns")
spending_report = df[['CustomerID', 'TotalSpend']]
print(spending_report)
# Output:
#   CustomerID  TotalSpend
# 0      C001       200.0
# 1      C002        50.0
# 2      C003        60.0
# 3      C004       600.0
# 4      C005         NaN

# Method 3: Using loc for label-based selection
# Use case: Select columns for a specific subset of rows (e.g., Premium customers)
print("\nMethod 3: Using loc to select 'CustomerSegment' and 'TotalSpend' for Premium customers")
premium_spending = df.loc[df['CustomerSegment'] == 'Premium', ['CustomerSegment', 'TotalSpend']]
print(premium_spending)
# Output:
#   CustomerSegment  TotalSpend
# 0        Premium       200.0
# 3        Premium       600.0

# Method 4: Using iloc for position-based selection
# Use case: Select the first two columns for a quick preview
print("\nMethod 4: Using iloc to select first two columns (CustomerID, TransactionDate)")
first_two_cols = df.iloc[:, [0, 1]]
print(first_two_cols)
# Output:
#   CustomerID TransactionDate
# 0      C001     2025-01-01
# 1      C002     2025-01-02
# 2      C003     2025-01-03
# 3      C004            NaN
# 4      C005     2025-01-05

# Method 5: Using filter() for pattern-based selection
# Use case: Select all columns containing 'Price' or 'Spend' for financial analysis
print("\nMethod 5: Using filter to select columns containing 'Price' or 'Spend'")
price_cols = df.filter(like='Price|Spend')
print(price_cols)
# Output:
#    UnitPrice  TotalSpend
# 0     100.0       200.0
# 1      50.0        50.0
# 2      20.0        60.0
# 3     150.0       600.0
# 4      60.0         NaN

# Additional Advanced Methods:

# Method 6: Using regex with filter()
# Use case: Select columns matching a complex pattern (e.g., columns related to customer info)
print("\nMethod 6: Using filter with regex to select customer-related columns")
customer_cols = df.filter(regex='Customer.*')
print(customer_cols)
# Output:
#   CustomerID CustomerSegment
# 0      C001        Premium
# 1      C002        Regular
# 2      C003        Regular
# 3      C004        Premium
# 4      C005        Regular

# Method 7: Conditional column selection with list comprehension
# Use case: Select numerical columns for statistical analysis
print("\nMethod 7: Selecting numerical columns using list comprehension")
numerical_cols = df[[col for col in df.columns if df[col].dtype in ['int64', 'float64']]]
print(numerical_cols)
# Output:
#    Quantity  UnitPrice  TotalSpend
# 0       2.0     100.0       200.0
# 1       1.0      50.0        50.0
# 2       3.0      20.0        60.0
# 3       4.0     150.0       600.0
# 4       NaN      60.0         NaN

# Method 8: Dynamic column selection based on conditions
# Use case: Select columns with missing values for data cleaning
print("\nMethod 8: Selecting columns with missing values")
cols_with_na = df[[col for col in df.columns if df[col].isnull().any()]]
print(cols_with_na)
# Output:
#   TransactionDate  Quantity  TotalSpend
# 0     2025-01-01       2.0       200.0
# 1     2025-01-02       1.0        50.0
# 2     2025-01-03       3.0        60.0
# 3            NaN       4.0       600.0
# 4     2025-01-05       NaN         NaN

# Method 9: Selecting columns for large datasets with usecols
# Use case: Load only specific columns from a large CSV to save memory
print("\nMethod 9: Using usecols to load specific columns from CSV")
df_subset = pd.read_csv('transactions.csv', usecols=['CustomerID', 'TotalSpend'])
print(df_subset)
# Output:
#   CustomerID  TotalSpend
# 0      C001       200.0
# 1      C002        50.0
# 2      C003        60.0
# 3      C004       600.0
# 4      C005         NaN

Original DataFrame:
  CustomerID TransactionDate ProductCategory  Quantity  UnitPrice  TotalSpend  \
0       C001      2025-01-01     Electronics       2.0      100.0       200.0
1       C002      2025-01-02        Clothing       1.0       50.0        50.0
2       C003      2025-01-03           Books       3.0       20.0        60.0
3       C004             NaN     Electronics       4.0      150.0       600.0
4       C005      2025-01-05        Clothing       NaN       60.0         NaN

  CustomerSegment Region
0         Premium  North
1         Regular  South
2         Regular   East
3         Premium   West
4         Regular  North

Method 1: Selecting 'CustomerID' column
0    C001
1    C002
2    C003
3    C004
4    C005
Name: CustomerID, dtype: object

Method 2: Selecting 'CustomerID' and 'TotalSpend' columns
  CustomerID  TotalSpend
0       C001       200.0
1       C002        50.0
2       C003        60.0
3       C004       600.0
4       C005         NaN

Method 3: Using loc to select 'CustomerSegment' and 'TotalSpend' for Premium customers
  CustomerSegment  TotalSpend
0         Premium       200.0
3         Premium       600.0

Method 4: Using iloc to select first two columns (CustomerID, TransactionDate)
  CustomerID TransactionDate
0       C001      2025-01-01
1       C002      2025-01-02
2       C003      2025-01-03
3       C004             NaN
4       C005      2025-01-05

Method 5: Using filter to select columns containing 'Price' or 'Spend'
Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

Method 6: Using filter with regex to select customer-related columns
  CustomerID CustomerSegment
0       C001         Premium
1       C002         Regular
2       C003         Regular
3       C004         Premium
4       C005         Regular

Method 7: Selecting numerical columns using list comprehension
   Quantity  UnitPrice  TotalSpend
0       2.0      100.0       200.0
1       1.0       50.0        50.0
2       3.0       20.0        60.0
3       4.0      150.0       600.0
4       NaN       60.0         NaN

Method 8: Selecting columns with missing values
  TransactionDate  Quantity  TotalSpend
0      2025-01-01       2.0       200.0
1      2025-01-02       1.0        50.0
2      2025-01-03       3.0        60.0
3             NaN       4.0       600.0
4      2025-01-05       NaN         NaN

Method 9: Using usecols to load specific columns from CSV
  CustomerID  TotalSpend
0       C001       200.0
1       C002        50.0
2       C003        60.0
3       C004       600.0
4       C005         NaN

### 2. Data Manipulation (21-40)

21. How do you filter rows based on a condition?
22. How do you sort a DataFrame by a column?
23. What is the groupby() function, and how is it used?
24. How do you merge two DataFrames?
25. What is the difference between merge() and join()?
26. How do you concatenate two DataFrames?
27. What is the purpose of the pivot() function?
28. How do you use the melt() function?
29. How do you apply a function to a column?
30. What is the difference between apply() and map()?
31. How do you create a new column based on existing columns?
32. How do you drop duplicate rows?
33. How do you select rows based on multiple conditions?
34. What is the query() function, and how is it used?
35. How do you change the data type of a column?
36. How do you convert a DataFrame to a NumPy array?
37. What is the purpose of the set\_index() function?
38. How do you reset the index of a DataFrame?
39. How do you select rows based on index labels?
40. What is the difference between drop() and del?

In [45]:
import pandas as pd
import numpy as np

In [46]:
# Sorting can be done using sort_values() for one or more columns.

# Method 1: Sort by a single column (ascending)
df = pd.DataFrame({'A': [3, 1, 4, 2], 'B': [5, 6, 7, 8]})
sorted_df = df.sort_values(by='A')
print(sorted_df)
# Output:
#    A  B
# 1  1  6
# 3  2  8
# 0  3  5
# 2  4  7

# Method 2: Sort by a single column (descending)
sorted_df = df.sort_values(by='A', ascending=False)
print(sorted_df)
# Output:
#    A  B
# 2  4  7
# 0  3  5
# 3  2  8
# 1  1  6

# Method 3: Sort by multiple columns
sorted_df = df.sort_values(by=['A', 'B'], ascending=[True, False])
print(sorted_df)
# Output: (Sorts by A ascending, then B descending within same A values)

# Method 4: Sort in-place
df.sort_values(by='A', inplace=True)
print(df)
# Output: Same as Method 1

   A  B
1  1  6
3  2  8
0  3  5
2  4  7
   A  B
2  4  7
0  3  5
3  2  8
1  1  6
   A  B
1  1  6
3  2  8
0  3  5
2  4  7
   A  B
1  1  6
3  2  8
0  3  5
2  4  7

In [ ]:
# Scenario: Filter an e-commerce dataset to find high-value orders (amount > $1000) from specific regions.

# Example Data
data = {
    'order_id': [1, 2, 3, 4, 5],
    'region': ['East', 'West', 'East', 'South', 'West'],
    'amount': [500, 1500, 2000, 800, 3000],
    'status': ['Completed', 'Pending', 'Completed', 'Cancelled', 'Completed']
}
df = pd.DataFrame(data)

# Method 1: Boolean Indexing (Single Condition)
filtered_single = df[df['amount'] > 1000]
print("Boolean Indexing (Single Condition):\n", filtered_single)
# Output:
#    order_id region  amount     status
# 1        2   West    1500    Pending
# 2        3   East    2000  Completed
# 4        5   West    3000  Completed

# Method 2: Boolean Indexing (Multiple Conditions with &)
filtered_multi = df[(df['amount'] > 1000) & (df['region'].isin(['East', 'West']))]
print("Boolean Indexing (Multiple Conditions):\n", filtered_multi)
# Output:
#    order_id region  amount     status
# 1        2   West    1500    Pending
# 2        3   East    2000  Completed
# 4        5   West    3000  Completed

# Method 3: Using loc with Boolean Condition
filtered_loc = df.loc[df['amount'] > 1000]
print("Using loc:\n", filtered_loc)
# Output: Same as Method 1

# Method 4: Using query
filtered_query = df.query('amount > 1000')
print("Using query:\n", filtered_query)
# Output: Same as Method 1

# Method 5: Using query with Multiple Conditions
filtered_query_multi = df.query('amount > 1000 and region in ["East", "West"]')
print("Query with Multiple Conditions:\n", filtered_query_multi)
# Output: Same as Method 2

# Method 6: Using where (returns NaN for non-matching rows)
filtered_where = df.where(df['amount'] > 1000)
print("Using where:\n", filtered_where)
# Output:
#    order_id region  amount     status
# 0       NaN    NaN     NaN        NaN
# 1       2.0   West  1500.0    Pending
# 2       3.0   East  2000.0  Completed
# 3       NaN    NaN     NaN        NaN
# 4       5.0   West  3000.0  Completed

# Method 7: Using mask (opposite of where, keeps non-matching rows)
filtered_mask = df.mask(df['amount'] <= 1000)
print("Using mask:\n", filtered_mask)
# Output: Same as Method 6

In [52]:
# groupby() groups data by one or more columns and applies aggregation functions (e.g., sum, mean).

# Example:
df = pd.DataFrame({'Category': ['A', 'A', 'B', 'B'], 'Value': [10, 20, 30, 40]})

# Method 1: Group by a single column and calculate mean
grouped = df.groupby('Category').mean()
print(grouped)
# Output:
#          Value
# Category      
# A         15.0
# B         35.0

# Method 2: Group by and apply multiple aggregations
grouped = df.groupby('Category').agg(['mean', 'sum'])
print(grouped)
# Output:
#          Value      
#           mean  sum
# Category           
# A         15.0   30
# B         35.0   70

# Method 3: Group by multiple columns
df['Subcategory'] = ['X', 'Y', 'X', 'Y']
grouped = df.groupby(['Category', 'Subcategory']).sum()
print(grouped)
# Output:
#                    Value
# Category Subcategory     
# A        X            10
#          Y            20
# B        X            30
#          Y            40

          Value
Category
A          15.0
B          35.0
         Value
          mean sum
Category
A         15.0  30
B         35.0  70
                      Value
Category Subcategory
A        X               10
         Y               20
B        X               30
         Y               40

In [ ]:
# Scenario: Sort a stock price dataset by daily returns and stock price to identify top performers.

# Example Data
data = {
    'stock': ['AAPL', 'GOOGL', 'MSFT', 'AMZN'],
    'price': [150.0, 2800.0, 300.0, 3400.0],
    'daily_return': [0.05, -0.02, 0.03, 0.01]
}
df = pd.DataFrame(data)

# Method 1: Sort by single column (ascending)
sorted_df = df.sort_values(by='daily_return')
print("Sort by daily_return (ascending):\n", sorted_df)
# Output:
#    stock   price  daily_return
# 1  GOOGL  2800.0        -0.02
# 3   AMZN  3400.0         0.01
# 2   MSFT   300.0         0.03
# 0   AAPL   150.0         0.05

# Method 2: Sort by single column (descending)
sorted_df_desc = df.sort_values(by='daily_return', ascending=False)
print("Sort by daily_return (descending):\n", sorted_df_desc)
# Output:
#    stock   price  daily_return
# 0   AAPL   150.0         0.05
# 2   MSFT   300.0         0.03
# 3   AMZN  3400.0         0.01
# 1  GOOGL  2800.0        -0.02

# Method 3: Sort by multiple columns
sorted_multi = df.sort_values(by=['daily_return', 'price'], ascending=[False, True])
print("Sort by daily_return (descending) and price (ascending):\n", sorted_multi)
# Output:
#    stock   price  daily_return
# 0   AAPL   150.0         0.05
# 2   MSFT   300.0         0.03
# 3   AMZN  3400.0         0.01
# 1  GOOGL  2800.0        -0.02

# Method 4: Sort in-place
df.sort_values(by='daily_return', inplace=True)
print("Sort in-place by daily_return:\n", df)
# Output: Same as Method 1

# Method 5: Handle missing values (na_position)
df_with_na = pd.DataFrame({
    'stock': ['AAPL', 'GOOGL', 'MSFT', 'AMZN'],
    'price': [150.0, np.nan, 300.0, 3400.0],
    'daily_return': [0.05, -0.02, 0.03, np.nan]
})
sorted_na_last = df_with_na.sort_values(by='daily_return', na_position='last')
print("Sort with NA last:\n", sorted_na_last)
# Output:
#    stock   price  daily_return
# 1  GOOGL     NaN        -0.02
# 2   MSFT   300.0         0.03
# 0   AAPL   150.0         0.05
# 3   AMZN  3400.0          NaN

# Method 6: Sort by index
df_sorted_index = df.sort_index()
print("Sort by index:\n", df_sorted_index)
# Output: Restores original index order

In [48]:
# Merging combines DataFrames based on common columns or indices using merge().

# Example:
df1 = pd.DataFrame({'ID': [1, 2, 3], 'Name': ['Alice', 'Bob', 'Charlie']})
df2 = pd.DataFrame({'ID': [1, 2, 4], 'Age': [25, 30, 35]})

# Method 1: Inner merge
merged = pd.merge(df1, df2, on='ID', how='inner')
print(merged)
# Output:
#    ID     Name  Age
# 0   1    Alice   25
# 1   2      Bob   30

# Method 2: Left merge
merged = pd.merge(df1, df2, on='ID', how='left')
print(merged)
# Output:
#    ID     Name  Age
# 0   1    Alice  25.0
# 1   2      Bob  30.0
# 2   3  Charlie   NaN

# Method 3: Right merge
merged = pd.merge(df1, df2, on='ID', how='right')
print(merged)
# Output:
#    ID     Name  Age
# 0   1    Alice   25
# 1   2      Bob   30
# 2   4      NaN   35

# Method 4: Outer merge
merged = pd.merge(df1, df2, on='ID', how='outer')
print(merged)
# Output:
#    ID     Name  Age
# 0   1    Alice  25.0
# 1   2      Bob  30.0
# 2   3  Charlie   NaN
# 3   4      NaN  35.0

   ID   Name  Age
0   1  Alice   25
1   2    Bob   30
   ID     Name   Age
0   1    Alice  25.0
1   2      Bob  30.0
2   3  Charlie   NaN
   ID   Name  Age
0   1  Alice   25
1   2    Bob   30
2   4    NaN   35
   ID     Name   Age
0   1    Alice  25.0
1   2      Bob  30.0
2   3  Charlie   NaN
3   4      NaN  35.0

What is the difference between merge() and join()?

In [53]:
# Scenario: Merge customer profiles with their order history to analyze purchase patterns in a retail system.

# Example Data
customers = pd.DataFrame({
    'customer_id': [101, 102, 103],
    'name': ['Alice', 'Bob', 'Charlie'],
    'city': ['New York', 'Los Angeles', 'Chicago']
})
orders = pd.DataFrame({
    'customer_id': [101, 102, 104],
    'order_amount': [1000, 500, 2000],
    'order_date': ['2023-01-01', '2023-02-01', '2023-03-01']
})

# Method 1: Inner merge
merged_inner = pd.merge(customers, orders, on='customer_id', how='inner')
print("Inner merge:\n", merged_inner)
# Output:
#    customer_id     name         city  order_amount order_date
# 0         101    Alice     New York         1000 2023-01-01
# 1         102      Bob  Los Angeles          500 2023-02-01

# Method 2: Left merge
merged_left = pd.merge(customers, orders, on='customer_id', how='left')
print("Left merge:\n", merged_left)
# Output:
#    customer_id     name         city  order_amount order_date
# 0         101    Alice     New York       1000.0 2023-01-01
# 1         102      Bob  Los Angeles        500.0 2023-02-01
# 2         103  Charlie      Chicago          NaN        NaN

# Method 3: Right merge
merged_right = pd.merge(customers, orders, on='customer_id', how='right')
print("Right merge:\n", merged_right)
# Output:
#    customer_id     name         city  order_amount order_date
# 0         101    Alice     New York         1000 2023-01-01
# 1         102      Bob  Los Angeles          500 2023-02-01
# 2         104      NaN          NaN         2000 2023-03-01

# Method 4: Outer merge
merged_outer = pd.merge(customers, orders, on='customer_id', how='outer')
print("Outer merge:\n", merged_outer)
# Output:
#    customer_id     name         city  order_amount order_date
# 0         101    Alice     New York       1000.0 2023-01-01
# 1         102      Bob  Los Angeles        500.0 2023-02-01
# 2         103  Charlie      Chicago          NaN        NaN
# 3         104      NaN          NaN       2000.0 2023-03-01

# Method 5: Merge on multiple keys
orders_multi = pd.DataFrame({
    'customer_id': [101, 102, 104],
    'city': ['New York', 'Los Angeles', 'Boston'],
    'order_amount': [1000, 500, 2000]
})
merged_multi_key = pd.merge(customers, orders_multi, on=['customer_id', 'city'], how='inner')
print("Merge on multiple keys:\n", merged_multi_key)
# Output:
#    customer_id     name         city  order_amount
# 0         101    Alice     New York         1000
# 1         102      Bob  Los Angeles          500

# Method 6: Merge with index
customers_index = customers.set_index('customer_id')
orders_index = orders.set_index('customer_id')
merged_index = pd.merge(customers_index, orders_index, left_index=True, right_index=True, how='inner')
print("Merge with index:\n", merged_index)
# Output:
#              name         city  order_amount order_date
# customer_id                                            
# 101         Alice     New York         1000 2023-01-01
# 102           Bob  Los Angeles          500 2023-02-01

Inner merge:
    customer_id   name         city  order_amount  order_date
0          101  Alice     New York          1000  2023-01-01
1          102    Bob  Los Angeles           500  2023-02-01
Left merge:
    customer_id     name         city  order_amount  order_date
0          101    Alice     New York        1000.0  2023-01-01
1          102      Bob  Los Angeles         500.0  2023-02-01
2          103  Charlie      Chicago           NaN         NaN
Right merge:
    customer_id   name         city  order_amount  order_date
0          101  Alice     New York          1000  2023-01-01
1          102    Bob  Los Angeles           500  2023-02-01
2          104    NaN          NaN          2000  2023-03-01
Outer merge:
    customer_id     name         city  order_amount  order_date
0          101    Alice     New York        1000.0  2023-01-01
1          102      Bob  Los Angeles         500.0  2023-02-01
2          103  Charlie      Chicago           NaN         NaN
3          104      NaN          NaN        2000.0  2023-03-01
Merge on multiple keys:
    customer_id   name         city  order_amount
0          101  Alice     New York          1000
1          102    Bob  Los Angeles           500
Merge with index:
               name         city  order_amount  order_date
customer_id
101          Alice     New York          1000  2023-01-01
102            Bob  Los Angeles           500  2023-02-01

In [50]:
# merge() combines DataFrames based on columns or indices, while join() combines based on indices.

# Example:
df1 = pd.DataFrame({'ID': [1, 2, 3], 'Name': ['Alice', 'Bob', 'Charlie']}, index=[1, 2, 3])
df2 = pd.DataFrame({'Age': [25, 30, 35]}, index=[1, 2, 4])

# Method 1: Using merge() (column-based)
merged = pd.merge(df1, df2, left_index=True, right_index=True, how='inner')
print(merged)
# Output:
#    ID     Name  Age
# 1   1    Alice   25
# 2   2      Bob   30

# Method 2: Using join() (index-based)
joined = df1.join(df2, how='inner')
print(joined)
# Output: Same as above

# Key Differences:
# - merge(): More flexible, allows merging on columns or indices, supports multiple join keys.
# - join(): Index-based, simpler for combining DataFrames with matching indices.
# - merge() supports 'on' parameter for columns; join() relies on index alignment.

   ID   Name  Age
1   1  Alice   25
2   2    Bob   30
   ID   Name  Age
1   1  Alice   25
2   2    Bob   30

In [ ]:
# Concatenation combines DataFrames along a specific axis using concat().

# Example:
df1 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df2 = pd.DataFrame({'A': [5, 6], 'B': [7, 8]})

# Method 1: Concatenate vertically (stack rows)
concatenated = pd.concat([df1, df2], axis=0)
print(concatenated)
# Output:
#    A  B
# 0  1  3
# 1  2  4
# 0  5  7
# 1  6  8

# Method 2: Concatenate horizontally (stack columns)
concatenated = pd.concat([df1, df2], axis=1)
print(concatenated)
# Output:
#    A  B  A  B
# 0  1  3  5  7
# 1  2  4  6  8

# Method 3: Ignore index to reset row indices
concatenated = pd.concat([df1, df2], ignore_index=True)
print(concatenated)
# Output:
#    A  B
# 0  1  3
# 1  2  4
# 2  5  7
# 3  6  8

In [54]:
# Scenario: Combine monthly sales data from different regions into a single DataFrame for a retail analytics dashboard.

# Example Data
jan_sales = pd.DataFrame({
    'region': ['East', 'West'],
    'sales': [10000, 15000],
    'month': ['Jan', 'Jan']
})
feb_sales = pd.DataFrame({
    'region': ['East', 'West'],
    'sales': [12000, 17000],
    'month': ['Feb', 'Feb']
})

# Method 1: Concatenate vertically (stack rows) with default index
concat_vertical = pd.concat([jan_sales, feb_sales], axis=0)
print("Vertical concatenation:\n", concat_vertical)
# Output:
#   region  sales month
# 0   East  10000   Jan
# 1   West  15000   Jan
# 0   East  12000   Feb
# 1   West  17000   Feb

# Method 2: Concatenate vertically and reset index
concat_ignore_index = pd.concat([jan_sales, feb_sales], axis=0, ignore_index=True)
print("Vertical concatenation with reset index:\n", concat_ignore_index)
# Output:
#   region  sales month
# 0   East  10000   Jan
# 1   West  15000   Jan
# 2   East  12000   Feb
# 3   West  17000   Feb

# Method 3: Concatenate horizontally (stack columns)
concat_horizontal = pd.concat([jan_sales, feb_sales], axis=1)
print("Horizontal concatenation:\n", concat_horizontal)
# Output:
#   region  sales month region  sales month
# 0   East  10000   Jan   East  12000   Feb
# 1   West  15000   Jan   West  17000   Feb

# Method 4: Concatenate with keys for multi-index
concat_keys = pd.concat([jan_sales, feb_sales], keys=['Jan', 'Feb'], axis=0)
print("Concatenation with multi-index keys:\n", concat_keys)
# Output:
#         region  sales month
# Jan 0   East  10000   Jan
#     1   West  15000   Jan
# Feb 0   East  12000   Feb
#     1   West  17000   Feb

# Method 5: Concatenate with non-matching columns
feb_sales_diff = pd.DataFrame({
    'region': ['East', 'West'],
    'revenue': [12000, 17000]
})
concat_diff = pd.concat([jan_sales, feb_sales_diff], axis=0)
print("Concatenate with non-matching columns:\n", concat_diff)
# Output:
#   region  sales month  revenue
# 0   East  10000   Jan      NaN
# 1   West  15000   Jan      NaN
# 0   East    NaN   NaN  12000.0
# 1   West    NaN   NaN  17000.0

Vertical concatenation:
   region  sales month
0   East  10000   Jan
1   West  15000   Jan
0   East  12000   Feb
1   West  17000   Feb
Vertical concatenation with reset index:
   region  sales month
0   East  10000   Jan
1   West  15000   Jan
2   East  12000   Feb
3   West  17000   Feb
Horizontal concatenation:
   region  sales month region  sales month
0   East  10000   Jan   East  12000   Feb
1   West  15000   Jan   West  17000   Feb
Concatenation with multi-index keys:
       region  sales month
Jan 0   East  10000   Jan
    1   West  15000   Jan
Feb 0   East  12000   Feb
    1   West  17000   Feb
Concatenate with non-matching columns:
   region    sales month  revenue
0   East  10000.0   Jan      NaN
1   West  15000.0   Jan      NaN
0   East      NaN   NaN  12000.0
1   West      NaN   NaN  17000.0

In [51]:
# pivot() reshapes a DataFrame from long to wide format, using one column for indices, another for columns, and a third for values.

# Example:
df = pd.DataFrame({
    'Date': ['2023-01', '2023-01', '2023-02', '2023-02'],
    'Category': ['A', 'B', 'A', 'B'],
    'Value': [10, 20, 30, 40]
})

# Using pivot
pivoted = df.pivot(index='Date', columns='Category', values='Value')
print(pivoted)
# Output:
# Category     A   B
# Date             
# 2023-01    10  20
# 2023-02    30  40

# Method 2: Handle missing values in pivot
pivoted = df.pivot(index='Date', columns='Category', values='Value').fillna(0)
print(pivoted)
# Output: Same as above, but fills NaN with 0 if applicable

Category   A   B
Date
2023-01   10  20
2023-02   30  40
Category   A   B
Date
2023-01   10  20
2023-02   30  40

In [ ]:
# Scenario: Create a pivot table to summarize sales by product and region for a retail dashboard.

# Example Data
data = {
    'date': ['2023-01', '2023-01', '2023-02', '2023-02'],
    'region': ['East', 'West', 'East', 'West'],
    'product': ['Phone', 'Phone', 'Laptop', 'Laptop'],
    'sales': [1000, 1500, 2000, 2500]
}
df = pd.DataFrame(data)

# Method 1: Basic pivot with aggregation (sum)
pivoted = df.pivot_table(index='date', columns='product', values='sales', aggfunc='sum')
print("Basic pivot:\n", pivoted)
# Output:
# product   Laptop  Phone
# date                 
# 2023-01      NaN   2500
# 2023-02   4500.0    NaN

# Method 2: Pivot with multiple columns
pivoted_multi = df.pivot(index='date', columns=['region', 'product'], values='sales')
print("Pivot with multi-column:\n", pivoted_multi)
# Output:
# region      East         West       
# product   Phone Laptop Phone Laptop
# date                              
# 2023-01  1000.0    NaN 1500.0    NaN
# 2023-02     NaN 2000.0    NaN 2500.0

# Method 3: Pivot with fillna to handle missing values
pivoted_fillna = df.pivot(index='date', columns='product', values='sales').fillna(0)
print("Pivot with fillna:\n", pivoted_fillna)
# Output:
# product   Laptop   Phone
# date                 
# 2023-01     0.0  1000.0
# 2023-02  2000.0    0.0

# Method 4: Pivot with multiple values (requires pivot_table)
# Note: pivot() does not support multiple values directly; use pivot_table() instead
pivoted_table = df.pivot_table(index='date', columns='product', values='sales', aggfunc='sum')
print("Pivot table for aggregation:\n", pivoted_table)
# Output: Same as Method 1 (for single value)

In [ ]:
# Scenario: Apply a discount to product prices based on a tiered pricing rule in an e-commerce dataset.

# Example Data
df = pd.DataFrame({
    'product': ['Phone', 'Laptop', 'Tablet'],
    'price': [1000, 2000, 500]
})

# Method 1: Apply with lambda function
df['discounted_price'] = df['price'].apply(lambda x: x * 0.9 if x > 1000 else x * 0.95)
print("Apply with lambda:\n", df)
# Output:
#   product  price  discounted_price
# 0  Phone   1000           950.0
# 1 Laptop   2000          1800.0
# 2 Tablet    500           475.0

# Method 2: Apply with defined function
def apply_discount(price):
    return price * 0.9 if price > 1000 else price * 0.95
df['discounted_price'] = df['price'].apply(apply_discount)
print("Apply with defined function:\n", df)
# Output: Same as Method 1

# Method 3: Vectorized operation with np.where
df['discounted_price'] = np.where(df['price'] > 1000, df['price'] * 0.9, df['price'] * 0.95)
print("Vectorized with np.where:\n", df)
# Output: Same as Method 1

# Method 4: Vectorized operation directly
df['discounted_price'] = df['price'] * [0.95, 0.9, 0.95]  # Custom logic per row
print("Vectorized directly:\n", df)
# Output: Same as Method 1

28. How do you use the melt() function?

In [58]:
# Scenario: Transform a wide-format sales report into a long format for time-series analysis in a retail system.

# Example Data
df = pd.DataFrame({
    'date': ['2023-01', '2023-02'],
    'East_Phone': [1000, 1200],
    'West_Phone': [1500, 1700],
    'East_Laptop': [2000, 2200]
})

# Method 1: Basic melt
melted = pd.melt(df, id_vars=['date'], value_vars=['East_Phone', 'West_Phone', 'East_Laptop'],
                 var_name='region_product', value_name='sales')
print("Basic melt:\n", melted)
# Output:
#       date region_product  sales
# 0  2023-01    East_Phone   1000
# 1  2023-02    East_Phone   1200
# 2  2023-01    West_Phone   1500
# 3  2023-02    West_Phone   1700
# 4  2023-01   East_Laptop   2000
# 5  2023-02   East_Laptop   2200

# Method 2: Melt with subset of value_vars
melted_subset = pd.melt(df, id_vars=['date'], value_vars=['East_Phone', 'West_Phone'],
                        var_name='region_product', value_name='sales')
print("Melt with subset of columns:\n", melted_subset)
# Output:
#       date region_product  sales
# 0  2023-01    East_Phone   1000
# 1  2023-02    East_Phone   1200
# 2  2023-01    West_Phone   1500
# 3  2023-02    West_Phone   1700

# Method 3: Melt without specifying value_vars (uses all non-id columns)
melted_all = pd.melt(df, id_vars=['date'], var_name='region_product', value_name='sales')
print("Melt all non-id columns:\n", melted_all)
# Output: Same as Method 1

Basic melt:
       date region_product  sales
0  2023-01     East_Phone   1000
1  2023-02     East_Phone   1200
2  2023-01     West_Phone   1500
3  2023-02     West_Phone   1700
4  2023-01    East_Laptop   2000
5  2023-02    East_Laptop   2200
Melt with subset of columns:
       date region_product  sales
0  2023-01     East_Phone   1000
1  2023-02     East_Phone   1200
2  2023-01     West_Phone   1500
3  2023-02     West_Phone   1700
Melt all non-id columns:
       date region_product  sales
0  2023-01     East_Phone   1000
1  2023-02     East_Phone   1200
2  2023-01     West_Phone   1500
3  2023-02     West_Phone   1700
4  2023-01    East_Laptop   2000
5  2023-02    East_Laptop   2200

30. What is the difference between apply() and map()?

In [ ]:
# Scenario: Transform customer ratings in a survey dataset, using apply() for complex logic and map() for simple mappings.

# Example Data
df = pd.DataFrame({
    'customer_id': [101, 102, 103],
    'rating': [3, 4, 5]
})

# Method 1: apply() with complex logic
df['rating_category'] = df['rating'].apply(lambda x: 'High' if x >= 4 else 'Low')
print("apply() with complex logic:\n", df)
# Output:
#    customer_id  rating rating_category
# 0         101       3           Low
# 1         102       4          High
# 2         103       5          High

# Method 2: map() with dictionary
rating_map = {3: 'Average', 4: 'Good', 5: 'Excellent'}
df['rating_label'] = df['rating'].map(rating_map)
print("map() with dictionary:\n", df)
# Output:
#    customer_id  rating rating_category rating_label
# 0         101       3           Low      Average
# 1         102       4          High         Good
# 2         103       5          High    Excellent

# Method 3: apply() with defined function
def categorize_rating(rating):
    return 'High' if rating >= 4 else 'Low'
df['rating_category'] = df['rating'].apply(categorize_rating)
print("apply() with defined function:\n", df)
# Output: Same as Method 1

# Method 4: map() with lambda
df['rating_label'] = df['rating'].map(lambda x: {3: 'Average', 4: 'Good', 5: 'Excellent'}[x])
print("map() with lambda:\n", df)
# Output: Same as Method 2

# Key Differences:
# - apply(): Works on Series or DataFrame, supports complex row/column operations.
# - map(): Works only on Series, best for simple element-wise mappings.

31. How do you create a new column based on existing columns?

In [ ]:
# Scenario: Calculate total cost (price * quantity) and apply tax in an inventory dataset.

# Example Data
df = pd.DataFrame({
    'item': ['Phone', 'Laptop', 'Tablet'],
    'price': [1000, 2000, 500],
    'quantity': [2, 1, 3]
})

# Method 1: Vectorized arithmetic
df['total_cost'] = df['price'] * df['quantity']
print("Vectorized arithmetic:\n", df)
# Output:
#     item  price  quantity  total_cost
# 0  Phone   1000        2        2000
# 1 Laptop   2000        1        2000
# 2 Tablet    500        3        1500

# Method 2: Using apply
df['total_cost'] = df.apply(lambda row: row['price'] * row['quantity'], axis=1)
print("Using apply:\n", df)
# Output: Same as Method 1

# Method 3: Using assign
df = df.assign(total_cost=df['price'] * df['quantity'])
print("Using assign:\n", df)
# Output: Same as Method 1

# Method 4: Complex logic with np.where
df['total_with_tax'] = np.where(df['price'] > 1000, 
                                df['price'] * df['quantity'] * 1.1, 
                                df['price'] * df['quantity'] * 1.05)
print("Complex logic with tax:\n", df)
# Output:
#     item  price  quantity  total_cost  total_with_tax
# 0  Phone   1000        2        2000          2100.0
# 1 Laptop   2000        1        2000          2200.0
# 2 Tablet    500        3        1500          1575.0

32. How do you drop duplicate rows?

In [ ]:
# Scenario: Remove duplicate customer entries in a CRM dataset based on email addresses.

# Example Data
df = pd.DataFrame({
    'email': ['a@example.com', 'a@example.com', 'b@example.com', 'b@example.com'],
    'name': ['Alice', 'Alicia', 'Bob', 'Bobby'],
    'age': [25, 26, 30, 30]
})

# Method 1: Drop duplicates based on all columns
df_no_duplicates = df.drop_duplicates()
print("Drop duplicates (all columns):\n", df_no_duplicates)
# Output:
#            email   name  age
# 0  a@example.com  Alice   25
# 1  a@example.com  Alicia  26
# 2  b@example.com    Bob   30
# 3  b@example.com  Bobby   30

# Method 2: Drop duplicates based on specific column
df_no_duplicates_email = df.drop_duplicates(subset='email', keep='first')
print("Drop duplicates by email (keep first):\n", df_no_duplicates_email)
# Output:
#            email   name  age
# 0  a@example.com  Alice   25
# 2  b@example.com    Bob   30

# Method 3: Drop duplicates, keep last
df_no_duplicates_last = df.drop_duplicates(subset='email', keep='last')
print("Drop duplicates by email (keep last):\n", df_no_duplicates_last)
# Output:
#            email   name  age
# 1  a@example.com  Alicia  26
# 3  b@example.com  Bobby   30

# Method 4: Drop duplicates in-place
df.drop_duplicates(subset='email', keep='first', inplace=True)
print("Drop duplicates in-place:\n", df)
# Output: Same as Method 2

# Method 5: Drop duplicates, ignore index
df_no_duplicates_reset = df.drop_duplicates(subset='email', keep='first').reset_index(drop=True)
print("Drop duplicates with reset index:\n", df_no_duplicates_reset)
# Output:
#            email   name  age
# 0  a@example.com  Alice   25
# 1  b@example.com    Bob   30

33. How do you select rows based on multiple conditions?

In [62]:
# Scenario: Filter high-value customers who spent over $500 and are from the East region in a retail dataset.

# Example Data
df = pd.DataFrame({
    'customer_id': [101, 102, 103, 104],
    'region': ['East', 'West', 'East', 'South'],
    'spend': [600, 400, 800, 1000],
    'age': [25, 30, 35, 40]
})

# Method 1: Boolean indexing with & (and)
filtered_and = df[(df['spend'] > 500) & (df['region'] == 'East')]
print("Boolean indexing (and):\n", filtered_and)
# Output:
#    customer_id region  spend  age
# 0         101   East    600   25
# 2         103   East    800   35

# Method 2: Boolean indexing with | (or)
filtered_or = df[(df['spend'] > 500) | (df['age'] < 30)]
print("Boolean indexing (or):\n", filtered_or)
# Output:
#    customer_id region  spend  age
# 0         101   East    600   25
# 2         103   East    800   35
# 3         104  South   1000   40

# Method 3: Using loc with multiple conditions
filtered_loc = df.loc[(df['spend'] > 500) & (df['region'] == 'East')]
print("Using loc:\n", filtered_loc)
# Output: Same as Method 1

# Method 4: Using query
filtered_query = df.query('spend > 500 and region == "East"')
print("Using query:\n", filtered_query)
# Output: Same as Method 1

# Method 5: Using isin for list-based conditions
filtered_isin = df[df['region'].isin(['East']) & (df['spend'] > 500)]
print("Using isin:\n", filtered_isin)
# Output: Same as Method 1

Boolean indexing (and):
    customer_id region  spend  age
0          101   East    600   25
2          103   East    800   35
Boolean indexing (or):
    customer_id region  spend  age
0          101   East    600   25
2          103   East    800   35
3          104  South   1000   40
Using loc:
    customer_id region  spend  age
0          101   East    600   25
2          103   East    800   35
Using query:
    customer_id region  spend  age
0          101   East    600   25
2          103   East    800   35
Using isin:
    customer_id region  spend  age
0          101   East    600   25
2          103   East    800   35

34. What is the query() function, and how is it used?

In [ ]:
# Scenario: Query employee data to find those with high salaries and in specific departments.

# Example Data
df = pd.DataFrame({
    'emp_id': [1, 2, 3, 4],
    'department': ['HR', 'IT', 'HR', 'Sales'],
    'salary': [50000, 80000, 60000, 70000],
    'years_experience': [2, 5, 3, 4]
})

# Method 1: Basic query with single condition
filtered_single = df.query('salary > 60000')
print("Query single condition:\n", filtered_single)
# Output:
#    emp_id department  salary  years_experience
# 1      2       IT   80000                5
# 3      4    Sales   70000                4

# Method 2: Query with multiple conditions
filtered_multi = df.query('salary > 60000 and department == "IT"')
print("Query multiple conditions:\n", filtered_multi)
# Output:
#    emp_id department  salary  years_experience
# 1      2       IT   80000                5

# Method 3: Query with variable
threshold = 60000
filtered_var = df.query('salary > @threshold')
print("Query with variable:\n", filtered_var)
# Output: Same as Method 1

# Method 4: Query with in clause
filtered_in = df.query('department in ["IT", "Sales"] and salary > 60000')
print("Query with in clause:\n", filtered_in)
# Output:
#    emp_id department  salary  years_experience
# 1      2       IT   80000                5
# 3      4    Sales   70000                4

# Method 5: Query with complex expression
filtered_complex = df.query('salary / years_experience > 15000')
print("Query with complex expression:\n", filtered_complex)
# Output:
#    emp_id department  salary  years_experience
# 1      2       IT   80000                5
# 3      4    Sales   70000                4

35. How do you change the data type of a column?

In [65]:
# Scenario: Convert transaction dates to datetime and amounts to float in a financial dataset.

# Example Data
df = pd.DataFrame({
    'transaction_id': [1, 2, 3],
    'date': ['2023-01-01', '2023-02-01', '2023-03-01'],
    'amount': ['1000.50', '2000.75', '1500.25']
})

# Method 1: Using astype to convert to float
df['amount'] = df['amount'].astype(float)
print("Using astype to float:\n", df.dtypes)
# Output:
# transaction_id      int64
# date              object
# amount           float64
# dtype: object

# Method 2: Using to_numeric for amount
df['amount'] = pd.to_numeric(df['amount'], errors='coerce')
print("Using to_numeric:\n", df.dtypes)
# Output: Same as Method 1

# Method 3: Convert date to datetime
df['date'] = pd.to_datetime(df['date'])
print("Convert date to datetime:\n", df.dtypes)
print(df)
# Output:
# transaction_id             int64
# date              datetime64[ns]
# amount                   float64
# dtype: object

# Method 4: Using astype for categorical
df['transaction_id'] = df['transaction_id'].astype(str)
print("Convert to string (categorical):\n", df.dtypes)
# Output:
# transaction_id            object
# date              datetime64[ns]
# amount                   float64
# dtype: object

# Method 5: Using convert_dtypes for optimal types
df = df.convert_dtypes()
print("Using convert_dtypes:\n", df.dtypes)
# Output:
# transaction_id    string[python]
# date              datetime64[ns]
# amount                   Float64
# dtype: object

Using astype to float:
 transaction_id      int64
date               object
amount            float64
dtype: object
Using to_numeric:
 transaction_id      int64
date               object
amount            float64
dtype: object
Convert date to datetime:
 transaction_id             int64
date              datetime64[ns]
amount                   float64
dtype: object
   transaction_id       date   amount
0               1 2023-01-01  1000.50
1               2 2023-02-01  2000.75
2               3 2023-03-01  1500.25
Convert to string (categorical):
 transaction_id            object
date              datetime64[ns]
amount                   float64
dtype: object
Using convert_dtypes:
 transaction_id    string[python]
date              datetime64[ns]
amount                   Float64
dtype: object

37. What is the purpose of the set_index() function?

In [ ]:
# Scenario: Set customer IDs as the index for faster lookup in a customer database.

# Example Data
df = pd.DataFrame({
    'customer_id': [101, 102, 103],
    'name': ['Alice', 'Bob', 'Charlie'],
    'purchase': [500, 600, 700]
})

# Method 1: Set single column as index
df_single = df.set_index('customer_id')
print("Set single index:\n", df_single)
# Output:
#             name  purchase
# customer_id               
# 101         Alice       500
# 102           Bob       600
# 103       Charlie       700

# Method 2: Set multiple columns as index
df_multi = df.set_index(['customer_id', 'name'])
print("Set multi-index:\n", df_multi)
# Output:
#                    purchase
# customer_id name           
# 101         Alice       500
# 102         Bob         600
# 103         Charlie     700

# Method 3: Set index in-place
df.set_index('customer_id', inplace=True)
print("Set index in-place:\n", df)
# Output: Same as Method 1

# Method 4: Append to existing index
df_append = df.set_index('name', append=True)
print("Append to existing index:\n", df_append)
# Output:
#                    purchase
# customer_id name           
# 101         Alice       500
# 102         Bob         600
# 103         Charlie     700

38. How do you reset the index of a DataFrame?

In [66]:
# Scenario: Reset the index of a filtered customer dataset to prepare for export.

# Example Data
df = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie'],
    'purchase': [500, 600, 700]
}, index=[101, 102, 103])

# Method 1: Reset index to default integer
df_reset = df.reset_index()
print("Reset index:\n", df_reset)
# Output:
#    index     name  purchase
# 0    101    Alice       500
# 1    102      Bob       600
# 2    103  Charlie       700

# Method 2: Reset index and drop old index
df_drop = df.reset_index(drop=True)
print("Reset and drop index:\n", df_drop)
# Output:
#       name  purchase
# 0    Alice       500
# 1      Bob       600
# 2  Charlie       700

# Method 3: Reset in-place
df.reset_index(inplace=True)
print("Reset in-place:\n", df)
# Output: Same as Method 1

# Method 4: Reset multi-index
df_multi = pd.DataFrame({
    'purchase': [500, 600, 700]
}, index=pd.MultiIndex.from_tuples([(101, 'A'), (102, 'B'), (103, 'C')], names=['id', 'group']))
df_multi_reset = df_multi.reset_index()
print("Reset multi-index:\n", df_multi_reset)
# Output:
#     id group  purchase
# 0  101     A       500
# 1  102     B       600
# 2  103     C       700

Reset index:
    index     name  purchase
0    101    Alice       500
1    102      Bob       600
2    103  Charlie       700
Reset and drop index:
       name  purchase
0    Alice       500
1      Bob       600
2  Charlie       700
Reset in-place:
    index     name  purchase
0    101    Alice       500
1    102      Bob       600
2    103  Charlie       700
Reset multi-index:
     id group  purchase
0  101     A       500
1  102     B       600
2  103     C       700

39. How do you select rows based on index labels?

In [67]:
# Scenario: Select specific customer records by their ID from a CRM dataset.

# Example Data
df = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie'],
    'purchase': [500, 600, 700]
}, index=[101, 102, 103])

# Method 1: Using loc with single index
selected_single = df.loc[101]
print("Select single index:\n", selected_single)
# Output:
# name       Alice
# purchase     500
# Name: 101, dtype: object

# Method 2: Using loc with multiple indices
selected_multi = df.loc[[101, 103]]
print("Select multiple indices:\n", selected_multi)
# Output:
#         name  purchase
# 101    Alice       500
# 103  Charlie       700

# Method 3: Using loc with slice
selected_slice = df.loc[101:102]
print("Select index slice:\n", selected_slice)
# Output:
#       name  purchase
# 101  Alice       500
# 102    Bob       600

# Method 4: Using loc with multi-index
df_multi = pd.DataFrame({
    'purchase': [500, 600, 700]
}, index=pd.MultiIndex.from_tuples([(101, 'A'), (102, 'B'), (103, 'C')], names=['id', 'group']))
selected_multi_index = df_multi.loc[(101, 'A')]
print("Select multi-index:\n", selected_multi_index)
# Output:
# purchase    500
# Name: (101, A), dtype: int64

Select single index:
 name        Alice
purchase      500
Name: 101, dtype: object
Select multiple indices:
         name  purchase
101    Alice       500
103  Charlie       700
Select index slice:
       name  purchase
101  Alice       500
102    Bob       600
Select multi-index:
 purchase    500
Name: (101, A), dtype: int64

40. What is the difference between drop() and del?

In [ ]:
# Scenario: Clean a marketing campaign dataset by removing irrelevant columns or rows.

# Example Data
df = pd.DataFrame({
    'campaign_id': [1, 2, 3],
    'clicks': [100, 200, 300],
    'impressions': [1000, 2000, 3000],
    'conversions': [10, 20, 30]
})

# Method 1: drop columns
df_drop_col = df.drop(columns='impressions')
print("Drop column:\n", df_drop_col)
# Output:
#    campaign_id  clicks  conversions
# 0           1     100          10
# 1           2     200          20
# 2           3     300          30

# Method 2: drop multiple columns
df_drop_multi = df.drop(columns=['impressions', 'conversions'])
print("Drop multiple columns:\n", df_drop_multi)
# Output:
#    campaign_id  clicks
# 0           1     100
# 1           2     200
# 2           3     300

# Method 3: drop rows
df_drop_row = df.drop(index=0)
print("Drop row:\n", df_drop_row)
# Output:
#    campaign_id  clicks  impressions  conversions
# 1           2     200         2000          20
# 2           3     300         3000          30

# Method 4: drop in-place
df.drop(columns='impressions', inplace=True)
print("Drop in-place:\n", df)
# Output:
#    campaign_id  clicks  conversions
# 0           1     100          10
# 1           2     200          20
# 2           3     300          30

# Method 5: Using del
del df['conversions']
print("Using del:\n", df)
# Output:
#    campaign_id  clicks
# 0           1     100
# 1           2     200
# 2           3     300

# Key Differences:
# - drop(): Removes rows or columns, supports non-inplace operations, flexible for multiple labels.
# - del: Removes columns only, always in-place, more memory-efficient for single columns.